services:
  frontend:
    container_name: frontend
    image: frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: vite.dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
